作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的索引、切片、以及屬性，皆需要注意使用方式<br>
陣列之中索引式由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [1]:
import numpy as np

In [ ]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [12]:
a = np.arange(0, 21, step=1)

In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
#2.呈上題，將以上數列取出偶數。

In [15]:
b = []
for num in a:
   if num%2 == 0:
       b.append(num)

In [16]:
b

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
#3.呈1題，將數列取出3的倍數。

In [25]:
c = []
for num in a:
    if num%3 == 0 and num!=0:
        c.append(num)

In [26]:
c

[3, 6, 9, 12, 15, 18]